### ISSUE TITLE
-a with -g gives funny output

### ISSUE THREAD

**Issue by auduny** [vgno/knife-psearch#4]
```knife psearch 'NOT virtualization_system:vmware' --no-color -g vgnett.enclosure_name -a dmi.system.product_name,cpu.real,memory.total````

If you add -a to -g the coloring is off and the indenting is also off. Just adding one -a makes it all line up (with no indent) multiple -a makes the indenting even more changed.

**Comment by auduny** [comment]
```
 hmg9-mesos-slave-01.int.vgnett.no:
 dmi.system.product_name: ProLiant DL380 G6
cpu.real:
   cpu.real: 2
 memory.total: 74052768kB
 sjakk-02.int.vgnett.no:
 dmi.system.product_name: ProLiant BL460c Gen8
cpu.real:
   cpu.real: 2
 memory.total: 131994948kB
 hdp-07.int.vgnett.no:
```
